/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_android_madv_glrenderer_MadvGLRenderer */

#define DEBUG 1

#define LOG_TAG "MADVGL"
#define ALOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#if DEBUG
#define ALOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, LOG_TAG, __VA_ARGS__)
#else
#define ALOGV(...)
#endif

#ifndef _Included_com_android_madv_glrenderer_MadvGLRenderer
#define _Included_com_android_madv_glrenderer_MadvGLRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    createNativeGLRenderer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_createNativeGLRenderer
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    releaseNativeGLRenderer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_releaseNativeGLRenderer
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setSourceTextures
 * Signature: (ZIILcom/android/madv/glrenderer/MadvGLRenderer/SizeF;Lcom/android/madv/glrenderer/MadvGLRenderer/SizeF;IZ)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setSourceTextures
        (JNIEnv *, jobject, jboolean, jint, jint, jobject, jobject, jint, jboolean);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    draw
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_draw
        (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setEulerAngles
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setEulerAngles
        (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setQuaternion
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setQuaternion
        (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    getDisplayMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_getDisplayMode
        (JNIEnv *, jobject);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setDisplayMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setDisplayMode
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    getIsYUVColorSpace
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_getIsYUVColorSpace
        (JNIEnv *, jobject);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setIsYUVColorSpace
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setIsYUVColorSpace
        (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    getFocalLength
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_getFocalLength
        (JNIEnv *, jobject);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setFocalLength
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setFocalLength
        (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    getYawRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_getYawRadius
        (JNIEnv *, jobject);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setYawRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setYawRadius
        (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    getPitchRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_getPitchRadius
        (JNIEnv *, jobject);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setPitchRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setPitchRadius
        (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    getBankRadius
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_getBankRadius
        (JNIEnv *, jobject);

/*
 * Class:     com_android_madv_glrenderer_MadvGLRenderer
 * Method:    setBankRadius
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_android_madv_glrenderer_MadvGLRenderer_setBankRadius
        (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
